FROM python:3.10 AS lite

WORKDIR /app

# Install pandoc and netcat
RUN apt-get update \
    && apt-get install -y pandoc netcat-openbsd \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.lite.txt .
RUN pip install --no-cache-dir -r requirements.lite.txt

COPY . .

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
